# Generated by Django 6.1 on 2026-08-11 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_client_email_client_last_name_client_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="client",
            name="password",
        ),
        migrations.RemoveField(
            model_name="client",
            name="username",
        ),
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
