# Generated by Django 6.1 on 2026-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
